export const COMMON_RULES = {
  required: () => ({ rule: (v) => v?.trim().length > 0, message: 'Este campo es requerido' }),
  minLength: (n) => ({ rule: (v) => v?.trim().length >= n, message: `Mínimo ${n} caracteres` }),
  lettersOnly: { rule: (v) => /^[a-zA-ZáéíóúÁÉÍÓÚñÑüÜ\s'-]+$/.test(v), message: 'Solo letras' },
  emailFormat: { rule: (v) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v), message: 'Formato de email inválido (ej: user@correo.com)' },
  passwordMin: (n) => ({ rule: (v) => v?.length >= n, message: `Mínimo ${n} caracteres` }),
  phoneFormat: { rule: (v) => !v || /^[+]{0,1}[0-9\s-()]+$/.test(v), message: 'Solo números, espacios, guiones, +, ()' },
  phoneDigits: (n) => ({ rule: (v) => !v || v.replace(/\D/g, '').length >= n, message: `Mínimo ${n} dígitos` }),
  patenteFormat: { rule: (v) => !v || /^[a-zA-Z0-9]{6,8}$/.test(v), message: '6-8 caracteres alfanuméricos' },
  timeFormat: { rule: (v) => !v || /^([01]\d|2[0-3]):[0-5]\d$/.test(v), message: 'Formato HH:MM' },
  integer: { rule: (v) => v === '' || v === undefined || v === null || (!isNaN(Number(v)) && Number.isInteger(Number(v))), message: 'Debe ser número entero' },
  minValue: (n) => ({ rule: (v) => v === '' || v === undefined || v === null || Number(v) >= n, message: `Debe ser ≥ ${n}` }),
  totalPositive: (v1, v2) => ({ rule: () => Number(v1 || 0) + Number(v2 || 0) > 0, message: 'La capacidad total debe ser > 0' }),
  atLeastOne: { rule: (v) => Array.isArray(v) && v.length > 0, message: 'Selecciona al menos un día' },
  nonEmpty: () => ({ rule: (v) => v !== '' && v !== null && v !== undefined, message: 'Selecciona una opción' }),
  horaBefore: (horaInicio, horaFin) => ({
    rule: () => !horaInicio || !horaFin || horaInicio < horaFin,
    message: 'Hora fin debe ser posterior a hora inicio',
  }),
};
